config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root 'user/environments#index'

  constraints subdomain: /.*/ do  
    namespace :user do
      resources :organizations, except: [:index, :destroy, :show]
      resources :users, except: [:show]
      resources :affiliates, only: [:index, :show] do
        resources :rewards, except: [:index, :show, :destroy]
      end
      resources :invites, only: [:new, :update, :create]
      resources :affiliate_campaigns
      resources :rewards
      resources :dashboards,  only: [:index]
      resources :notifications, only: [:index, :update]
      resources :environments, only: [:index]
    end

    devise_for :clients, controllers: {
      sessions: 'clients/sessions',
      registrations: 'clients/registrations',
      passwords: 'clients/passwords'
    }

    namespace :client do
      resources :awards
      resources :rewards
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :role
  has_one :organization, through: :role

  has_many :accessibilities
  has_many :mentions
  has_many :notifications

  validates :full_name, presence: true
  validates :phone_number, presence: true
end

app/controllers/user/affiliate_campaigns_controller.rb
# frozen_string_literal: true

class User::AffiliateCampaignsController < UserController
  before_action :set_affiliate_campaign

  def show; end

  def affiliate; end

  def share_with_affiliate; end

  def share_with_lead; end

  def edit
    @reward = organization.decorate.reward_main
  end

  def update
    result = ::Users::AffiliateCampaigns::Update.result(
      attributes: affiliate_campaigns_params,
      affiliate_campaign: @affiliate_campaign
    )

    if result.success?
      redirect_to user_affiliate_campaign_path(@affiliate_campaign), notice: 'atualizado'
    else
      flash[:alert] = result.error

      render :edit
    end
  end

  private

  def affiliate_campaign_params
    params.require(:affiliate_campaign).permit(
      :title, :subtitle, :description, :title_form, :subtitle_form,
      :rule_title, :rule_description, :background_color, :primary_color, :secondary_color,
      rewards_attributes: [:id, :to_affiliate, :to_lead, :social_network, :username]
    ).merge(organization: current_user.organization).to_h
  end

  def set_affiliate_campaign
    @affiliate_campaign = policy_scope(AffiliateCampaign).find(params[:id])
  end
end

app/controllers/user/affiliates_controller.rb
# frozen_string_literal: true

class User::AffiliatesController < UserController
  def index
    @q = policy_scope(Affiliate).ransack(params[:q])
    result = @q.result(distinct: true).order(created_at: :desc)
    @pagy, @affiliates = pagy(result, items: 10)
  end
end

app/controllers/user/dashboards_controller.rb
# frozen_string_literal: true

class User::DashboardsController < UserController
  def index
  end
end

app/controllers/user/environments_controller.rb
# frozen_string_literal: true

class User::EnvironmentsController < UserController
  def index
    redirect_to user_dashboards_path if current_user.organization.present?
  end
end

app/controllers/user/invites_controller.rb
# frozen_string_literal: true

class User::InvitesController < UserController
  before_action :set_invite, only: %i[destroy]

  def index
    @q = policy_scope(Invite).ransack(params[:q])
    result = @q.result(distinct: true).order(created_at: :desc)
    @pagy, @invites = pagy(result, items: 10)
  end
  
  def create
    result = ::Users::Invites::Create.result(
      attributes: invites_params
    )

    if result.success?
      redirect_to user_invites_path, notice: 'criado'
    else
      redirect_to user_invites_path, alert: result.error
    end
  end

  def destroy
    result = ::Users::Invites::Destroy.result(
      invite: @invite
    )

    if result.success?
      redirect_to user_invites_path, notice: 'removido'
    else
      redirect_to user_invites_path, alert: result.error
    end
  end

  private

  def invite_params
    params.require(:invite).permit(:role_type, :email)
      .merge(organization: current_user.organization).to_h
  end

  def set_invite
    @invite = policy_class(Invite).find(params[:id])
  end
end

app/controllers/user/leads_controller.rb
# frozen_string_literal: true

class User::LeadsController < UserController
  before_action :set_lead, only: %i[destroy]

  def index
    @q = policy_scope(Lead).ransack(params[:q])
    result = @q.result(distinct: true).order(created_at: :desc)
    @pagy, @leads = pagy(result, items: 10)
  end

  def new
    @lead = Lead.new
  end

  def edit; end

  def create
    result = ::Users::Leads::Create.result(
      attributes: leads_params
    )

    if result.success?
      redirect_to user_leads_path, notice: 'criado'
    else
      redirect_to user_leads_path, alert: result.error
    end
  end

  def update
    result = ::Users::Leads::Update.result(
      attributes: leads_params,
      lead: @lead
    )

    if result.success?
      redirect_to user_leads_path, notice: 'criado'
    else
      redirect_to user_leads_path, alert: result.error
    end
  end

  private

  def lead_params
    params.require(:lead).permit(:full_name, :email, :phone_number)
      .merge(organization: current_user.organization).to_h
  end

  def set_lead
    @lead = policy_scope(Lead).find(params[:id])
  end
end

app/controllers/user/manager/accessibilities_controller.rb
# frozen_string_literal: true

class User::Manager::AccessibilitiesController < User::Manager::ManagerController
  before_action :set_project
  before_action :set_accessibility, except: [:index, :create, :new]

  def index
    @q = policy_scope(Accessibility).where(project: @project).joins(:roles).where.not(roles: { role_type: 'customer' }).ransack(params[:q])
    result = @q.result(distinct: true).includes(:project, :user).order(description: :asc)
    @pagy, @accessibilities = pagy(result, items: 10)
  end

  def new
    @accessibility = Accessibility.new
  end

  def edit; end

  def update
    result = ::Users::Manager::Accessibility::Employees::Update.result(
      accessibility: @accessibility,
      attributes: accessibility_params
    )

    if result.success?
      redirect_to user_provider_manager_project_folder_path(@project, result.folder.foldable), notice: 'atualizado'
    else
      @message_error = result.error
      @accessibility = result.accessibility

      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    result = ::Users::Manager::Accessibility::Employees::Destroy.result(
      folder: @accessibility
    )

    if result.success?
      
    else
      
    end
  end

  private

  def accessibility_params
    params.require(:accessibility).permit(:user_id, :allows).merge(project: @project).to_h
  end

  def set_accessibility
    @accessibility = policy_scope(Accessibility).find(params[:id])
  end

  def set_group
    @group = policy_scope(Group).friendly.find(params[:group_id])
  end
end

app/controllers/user/manager/clients_controller.rb
# frozen_string_literal: true

class User::Manager::ClientsController < User::Manager::ManagerController
  before_action :set_project
  before_action :set_accessibility, except: [:index, :create, :new]

  def index
    @q = policy_scope(Accessibility).where(project: @project).joins(:roles).where(roles: { role_type: 'customer' }).ransack(params[:q])
    result = @q.result(distinct: true).includes(:project, :user).order(description: :asc)
    @pagy, @accessibilities = pagy(result, items: 10)
  end

  def destroy
    result = ::Users::Manager::Accessibility::Destroy.result(
      folder: @accessibility
    )

    if result.success?
      
    else
      
    end
  end

  private

  def set_accessibility
    @accessibility = policy_scope(Accessibility).find(params[:id])
  end

  def set_group
    @group = policy_scope(Group).friendly.find(params[:group_id])
  end
end

app/controllers/user/notifications_controller.rb
# frozen_string_literal: true

class User::LeadsController < UserController
  before_action :set_lead, only: %i[destroy]

  def index
    @lead = organization.lead
  end

  
  private

  def set_lead
    @lead = policy_scope(Lead).find(params[:id])
  end
end

app/controllers/user/organizations_controller.rb
# frozen_string_literal: true

class User::OrganizationsController < UserController
  before_action :set_organization, only: %i[edit update]

  def new
    @organization = Organization.new
  end

  def edit; end

  def create
    result = ::Users::Organizations::Create::Received.result(
      owner: current_user,
      attributes: organization_params
    )

    if result.success?
      redirect_to user_affiliate_campaign_path(subdomain: result.organization.slug, id: result.organization.affiliate_campaign), notice: 'Sua organização foi cadastrada'
    else
      flash[:alert] = result.error
      @organization = result.organization

      render :new
    end
  end

  def update
    result = ::Users::Organizations::Update.result(
      owner: current_user,
      attributes: organization_params
    )

    if result.success?
      flash[:notice] = 'Sua organização foi atualizada'
      render :edit
    else
      flash[:alert] = result.error
      render :edit
    end
  end

  private

  def organization_params
    params.require(:organization).permit(:title, :email, :phone_number).to_h
  end

  def set_organization
    @organization = policy_scope(Organization).friendly.find(params[:id])

    authorize @organization
  end
end

app/controllers/user/partnerships_controller.rb
# frozen_string_literal: true

class User::PartnershipsController < UserController
  before_action :set_partnership

  def show; end

  def affiliate; end

  def share_with_affiliate; end

  def share_with_lead; end

  def edit
    @reward = organization.decorate.reward_main
  end

  def update
    result = ::Users::Partnerships::Update.result(
      attributes: partnerships_params,
      partnership: @partnership
    )

    if result.success?
      redirect_to user_partnership_path(@partnership), notice: 'atualizado'
    else
      flash[:alert] = result.error

      render :edit
    end
  end

  private

  def partnership_params
    params.require(:partnership).permit(
      :title, :subtitle, :description, :title_form, :subtitle_form,
      :rule_title, :rule_description, :background_color, :primary_color, :secondary_color,
      rewards_attributes: [:id, :to_affiliate, :to_lead, :social_network, :username]
    ).merge(organization: current_user.organization).to_h
  end

  def set_partnership
    @partnership = policy_scope(Partnership).find(params[:id])
  end
end

app/controllers/user/provider/roles_controller.rb
# frozen_string_literal: true

class User::Provider::RolesController < User::Provider::ProviderController
  before_action :set_user, only: %i[edit update destroy]

  def index
    @q = policy_scope(User).joins(:roles).where.not(roles: { role_type: 'customer'}).ransack(params[:q])
    result = @q.result(distinct: true).order(created_at: :desc)
    @pagy, @users = pagy(result, items: 10)
  end

  def new
    @user = User.new
    @role = Role.new
  end

  def create
    result = ::Provider::Roles::Create.result(
      attributes: user_params
    )

    if result.success?
      redirect_to user_provider_roles_path(result.user), notice: 'criado'
    else
      flash[:alert] = result.error
      @user = result.user

      render :new
    end
  end

  def update
    result = ::Provider::Roles::Update.result(
      user: @user,
      attributes: user_params
    )

    if result.success?
      redirect_to edit_user_provider_role_path(result.user), notice: 'atualizado'
    else
      flash[:alert] = result.error

      render :edit
    end
  end

  def destroy
    result = ::Provider::Roles::Destroy.result(
      user: @user,
      attributes: user_params
    )

    if result.success?
      redirect_to user_provider_users_path, notice: 'Removido'
    else
      flash[:alert] = result.error

      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :full_name, :email, role: [:role_type]
    ).to_h
  end

  def set_user
    @user = policy_class(Project).friendly.find(params[:id])
  end
end

app/controllers/user/provider/users_controller.rb
# frozen_string_literal: true

class User::Provider::RolesController < User::Provider::ProviderController
  before_action :set_user, only: %i[edit update destroy]

  def index
    @q = policy_scope(User).joins(:roles).where.not(roles: { role_type: 'customer'}).ransack(params[:q])
    result = @q.result(distinct: true).order(created_at: :desc)
    @pagy, @users = pagy(result, items: 10)
  end

  def new
    @user = User.new
    @role = Role.new
  end

  def create
    result = ::Provider::Roles::Create.result(
      attributes: user_params
    )

    if result.success?
      redirect_to user_provider_roles_path(result.user), notice: 'criado'
    else
      flash[:alert] = result.error
      @user = result.user

      render :new
    end
  end

  def update
    result = ::Provider::Roles::Update.result(
      user: @user,
      attributes: user_params
    )

    if result.success?
      redirect_to edit_user_provider_role_path(result.user), notice: 'atualizado'
    else
      flash[:alert] = result.error

      render :edit
    end
  end

  def destroy
    result = ::Provider::Roles::Destroy.result(
      user: @user,
      attributes: user_params
    )

    if result.success?
      redirect_to user_provider_users_path, notice: 'Removido'
    else
      flash[:alert] = result.error

      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :full_name, :email, role: [:role_type]
    ).to_h
  end

  def set_user
    @user = policy_class(Project).friendly.find(params[:id])
  end
end

app/controllers/user/rewards_controller.rb
# frozen_string_literal: true

class User::RewardsController < UserController
  before_action :set_reward, only: %i[destroy]

  def index
  end

  def new
    @reward = Reward.new
  end

  def create
    result = ::Users::Rewards::Create.result(
      attributes: rewards_params
    )

    if result.success?
      redirect_to user_rewards_path, notice: 'criado'
    else
      redirect_to user_rewards_path, alert: result.error
    end
  end

  def destroy
    result = ::Users::Rewards::Destroy.result(reward: @reward)

    if result.success?
      redirect_to user_rewards_path, notice: 'removido'
    else
      redirect_to user_rewards_path, alert: result.error
    end
  end

  private

  def reward_params
    params.require(:reward).permit(:affiliate_id, :lead_id)
  end

  def set_reward
    @reward = policy_scope(Reward).find(params[:id])
  end
end

app/controllers/user/users_controller.rb
# frozen_string_literal: true

class User::UsersController < UserController
  before_action :set_user, only: %i[edit update destroy]

  def index
    @q = policy_scope(User).ransack(params[:q])
    result = @q.result(distinct: true).order(created_at: :desc)
    @pagy, @users = pagy(result, items: 10)
  end

  def update
    result = ::Users::Roles::Update.result(
      user: @user,
      attributes: user_params
    )

    if result.success?
      redirect_to user_users_path, notice: 'atualizado'
    else
      flash[:alert] = result.error

      render :edit
    end
  end

  def destroy
    result = ::Users::Roles::Destroy.result(
      user: @user,
      attributes: user_params
    )

    if result.success?
      redirect_to user_users_path, notice: 'Removido'
    else
      redirect_to user_users_path, alert: result.error
    end
  end

  private

  def user_params
    params.require(:user).permit(
      role: [:role_type]
    ).to_h
  end

  def set_user
    @user = policy_class(Project).friendly.find(params[:id])
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  before_action :authenticate_user!, :confirm_invite, :authorize_organization

  def policy_scope(scope)
    super([:user, scope])
  end

  def authorize(record, query = nil)
    super([:user, record], query)
  end

  private

  def confirm_invite
    if session[:invitation_key].present?
      result = Users::Invites::Confirm.result(user: current_user, invite_key: session[:invitation_key])

      session[:invitation_key] = nil if result.success?
    end
  end

  def authorize_organization
    return if controller_path.include?('user/environments') || (controller_path.include?('user/organizations') && ['new', 'create'].include?(action_name))

    authorize(organization) 
  end

  def organization
    return if request.subdomain.blank?
    @organization = Organization.find_by!(slug: request.subdomain)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/views/user/page_award_templates/afiliado.html.haml
.layout-wrapper{style: 'background-color: yellow'}
  .layout-container
    .authentication-wrapper.authentication-basic.container-p-y
      .authentication-inner.py-4{style: 'max-width: 1000px;'}
        .p-2.mb-3
          .col-12
            = link_to 'Voltar', user_award_path(@award), class: 'btn btn-secondary'
            = link_to 'Editar', user_award_path(@award), class: 'btn btn-dark'

        .card
          .col-12
            .row.p-5.align-items-center
              .col-7
                %h2.display-5.mb-3.fw-semibold.lh-sm Crie sua Primeira Campanha de Indicação 👋
                %h4.mb-3 Crie sua Primeira Campanha de Indicação 👋
                %p.lead.fw-normal
                  Converta seus visitantes em indicadores, consiga mais clientes.

              .col-5
                .card-body
                  .col-12
                    %h4.mb-2 Bem-vindo ao Agenduu 👋
                    %p.mb-4 Faça login na sua conta
                    .form-floating.mb-3
                      %input.form-control
                      %label Nome Completo
                    .form-floating.mb-3
                      %input.form-control
                      %label Celular
                    .form-floating.mb-3
                      %input.form-control
                      %label Email
                    = link_to new_user_award_path, class: 'btn btn-info mb-3' do
                      %i.menu-icon.tf-icons.bx.bx-rocket
                      Compartilhar e Ganhar
                    %br
                    = link_to new_user_award_path, class: 'btn btn-warning mb-3' do
                      %i.menu-icon.tf-icons.bx.bx-user
                      Já Indiquei
            %hr
            .p-5.align-items-center
              %h2.fw-semibold Regras
              %p
                Converta seus visitantes em indicadores, consiga mais clientes.

app/views/user/page_award_templates/edit.html.haml
.layout-wrapper{style: 'background-color: yellow'}
  .layout-container
    .authentication-wrapper.authentication-basic.container-p-y
      .authentication-inner.py-4{style: 'max-width: 1000px;'}
        .p-2.mb-3
          .col-12
            = link_to 'Voltar', user_award_path(@award), class: 'btn btn-secondary'
            = link_to 'Editar', user_award_path(@award), class: 'btn btn-dark'

        .card
          .col-12
            .row.p-5.align-items-center
              .col-7
                %h2.display-5.mb-3.fw-semibold.lh-sm Nome da Empresa 🤝
                %h4.mb-3 Seu Código é 441B
                %p.lead.fw-normal
                  Converta seus visitantes em indicadores, consiga mais clientes.


              .col-5
                .card-body
                  .mb-3
                    %button.btn.btn-dark.btn-lg{type: "button"}
                      %span.tf-icons.bx.bxl-whatsapp
                      Fale Conosco

app/views/user/page_award_templates/share_code.html.haml
.layout-wrapper{style: 'background-color: yellow'}
  .layout-container
    .authentication-wrapper.authentication-basic.container-p-y
      .authentication-inner.py-4{style: 'max-width: 1000px;'}
        .p-2.mb-3
          .col-12
            = link_to 'Voltar', user_award_path(@award), class: 'btn btn-secondary'
            = link_to 'Editar', user_award_path(@award), class: 'btn btn-dark'

        .card
          .col-12
            .row.p-5.align-items-center
              .col-7
                %h2.display-5.mb-3.fw-semibold.lh-sm Seu Código é 441B 🚀
                %h4.mb-3 Compartilhe seu código ou link com quem você conhece.
                %p.lead.fw-normal
                  fjasdad.localhost:3000/indicar

                %br
                  = link_to new_user_award_path, class: 'btn btn-dark mb-3' do
                    %i.menu-icon.tf-icons.bx.bx-copy
                    Copiar Link
              .col-5
                .card-body
                  .col-12
                    %h4.mb-2 Compartilhe Aqui 👇 
                    .demo-inline-spacing
                      %button.btn.btn-icon.btn-primary{type: "button"}
                        %span.tf-icons.bx.bxl-facebook
                      %button.btn.btn-icon.btn-danger{type: "button"}
                        %span.tf-icons.bx.bxl-instagram
                      %button.btn.btn-icon.btn-success{type: "button"}
                        %span.tf-icons.bx.bxl-whatsapp
                      %button.btn.btn-icon.btn-dark{type: "button"}
                        %span.tf-icons.bx.bxl-tiktok
                      %button.btn.btn-icon.btn-info{type: "button"}
                        %span.tf-icons.bx.bxl-twitter
            %hr
            .p-5.align-items-center
              %h2.fw-semibold Regras
              %p
                Converta seus visitantes em indicadores, consiga mais clientes.